branches:
  only:
    - master

language: go

go:
  - "1.9"

install: go get github.com/stretchr/testify

script:
  - export GOPATH=$PWD
  - go test luago/...
  - go install luago/standalone/lua
  - ./bin/lua ./test/Lua534TestSuites/vararg.lua     | grep -q OK
  - ./bin/lua ./test/Lua534TestSuites/locals.lua     | grep -q OK
  - ./bin/lua ./test/Lua534TestSuites/closure.lua    | grep -q OK
  - ./bin/lua ./test/Lua534TestSuites/constructs.lua | grep -q OK
  - ./bin/lua ./test/Lua534TestSuites/events.lua     | grep -q OK
